
"""Application constants."""

# User Roles
ROLE_ADMIN = "admin"
ROLE_SCHOOL = "school"
ROLE_CITIZEN = "citizen"

VALID_ROLES = [ROLE_ADMIN, ROLE_SCHOOL, ROLE_CITIZEN]

# AQI Categories
AQI_GOOD = 50
AQI_MODERATE = 100
AQI_UNHEALTHY_SENSITIVE = 150
AQI_UNHEALTHY = 200
AQI_VERY_UNHEALTHY = 300
AQI_HAZARDOUS = 500

# NGSI-LD Entity Types
ENTITY_TYPE_AIR_QUALITY = "AirQualityObserved"
ENTITY_TYPE_WEATHER = "WeatherObserved"
ENTITY_TYPE_ENERGY = "EnergyData"
ENTITY_TYPE_SCHOOL = "School"
ENTITY_TYPE_GREEN_ACTION = "GreenAction"

# Correlations
MIN_CORRELATION_THRESHOLD = 0.3
STRONG_CORRELATION = 0.7
MODERATE_CORRELATION = 0.5

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
